# docker compose for local development
# this allows for hot reloading of the app
version: '3'
services:
  web:
    build: './app-web/'
    env_file: './app-web/.env.production'
    volumes:
      - './app-web/:/home/app'
      # a hack to ignore node_modules so that local version, 
      # if existing does not mount ontop of the images installed version
      - '/home/app/node_modules' 
    ports:
      - '8000:8000'